AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for Chiikawa Psychological Test LineBot Workshop resources"

Parameters:
  ProjectName:
    Type: String
    Default: auto-chiikawa
    Description: Project name for resource naming

  # Line Bot Configuration when setting stack
  ChannelAccessToken:
    Type: String
    Description: LINE Bot Channel Access Token
    NoEcho: true

  ChannelSecret:
    Type: String
    Description: LINE Bot Channel Secret
    NoEcho: true

Resources:
  # S3 Bucket for Lambda Code
  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${ProjectName}-lambda-code
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # S3 Bucket for Generated Images
  GeneratedImagesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${ProjectName}-generated-images
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - "*"
            MaxAge: 3600
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # DynamoDB Table
  ConversationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ProjectName}-conversations
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # IAM Role for Lambda functions
  LambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-lambda-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub ${ProjectName}-lambda-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                Resource: !GetAtt ConversationTable.Arn
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrockAgent:InvokeAgent
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt LambdaCodeBucket.Arn
                  - !Sub ${LambdaCodeBucket.Arn}/*
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource:
                  - !GetAtt GeneratedImagesBucket.Arn
                  - !Sub ${GeneratedImagesBucket.Arn}/*

  # Lambda function for handling webhook requests
  LineBotWebhookHandler:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-linebot
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaIAMRole.Arn
      Code: # Prefered to use S3
        ZipFile: |
          def lambda_handler(event, context):
            return {
              'statusCode': 200,
              'body': 'This is a dummy method, replace it.'
            }
      Runtime: python3.11
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          TABLE_NAME: !Ref ConversationTable
          CHANNEL_ACCESS_TOKEN: !Ref ChannelAccessToken
          CHANNEL_SECRET: !Ref ChannelSecret

  # API Gateway REST API
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${ProjectName}-api
      Description: API for Chiikawa psychological test LineBot

  # API Gateway method
  RootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !GetAtt ApiGateway.RootResourceId
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LineBotWebhookHandler.Arn}/invocations

  # API Gateway deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: RootMethod
    Properties:
      RestApiId: !Ref ApiGateway

  # API Gateway stage
  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref ApiGateway
      DeploymentId: !Ref ApiDeployment
      StageName: prod

  # Lambda permission for API Gateway
  WebhookHandlerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LineBotWebhookHandler
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/POST/

  # SageMaker Notebook Instance Role
  NotebookInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-notebook-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess

  # SageMaker Notebook Instance
  NotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      NotebookInstanceName: !Sub ${ProjectName}-notebook
      InstanceType: ml.t3.medium
      RoleArn: !GetAtt NotebookInstanceRole.Arn
      VolumeSizeInGB: 5

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod

  NotebookInstanceUrl:
    Description: URL for the SageMaker Notebook Instance
    Value: !Sub https://console.aws.amazon.com/sagemaker/home?region=${AWS::Region}#/notebook-instances/openNotebook/${ProjectName}-notebook

  DynamoDBTableName:
    Description: Name of the DynamoDB table
    Value: !Ref ConversationTable

  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref LineBotWebhookHandler
